name: WakaTime Readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 19 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-oos/alex-oos@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
